language: python
python:
  - 2.6
  - 2.7

# whitelist
branches:
  only:
    - develop

install:
  - pip install cheetah

before_script:
  - cd ./tests
  - chmod +x ./all_tests.py
  
script:
  - ./all_tests.py
